# Generated by Django 5.1.15 on 2026-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='logs',
            field=models.JSONField(default=list),
        ),
    ]
