# Generated by Django 5.1.15 on 2026-09-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcriptionjob_error_message_transcriptionjob_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunPodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runpod_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('pod_id', models.CharField(blank=True, default='', max_length=100)),
                ('pod_host', models.CharField(blank=True, default='', max_length=255)),
                ('pod_ssh_port', models.IntegerField(default=22)),
                ('ssh_key_path', models.CharField(default='~/.ssh/id_rsa', max_length=255)),
                ('hf_token', models.CharField(blank=True, default='', max_length=255)),
                ('local_proxy_port', models.IntegerField(default=8005)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RunPod Configuration',
                'verbose_name_plural': 'RunPod Configuration',
            },
        ),
    ]
