# Generated by Django 5.1.15 on 2026-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_runpodconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='runpodconfig',
            name='provision_gpu_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='runpodconfig',
            name='provision_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='runpodconfig',
            name='provision_status',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.AddField(
            model_name='runpodconfig',
            name='provisioned_pod_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
